apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobsight-pro
  namespace: jobsight
  labels:
    app: jobsight-pro
  annotations:
    doppler.com/project: jobsight       # 👈 Doppler project name
    doppler.com/config: production      # 👈 Doppler config name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobsight-pro
  template:
    metadata:
      labels:
        app: jobsight-pro
      annotations:
        doppler.com/enable: "true"      # 👈 Enable Doppler secret injection
    spec:
      containers:
        - name: jobsight-pro
          image: "${ACR_NAME}.azurecr.io/jobsight-pro:${IMAGE_TAG}"
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
            - name: ENVIRONMENT
              value: "production"
            # No need to manually add secrets here — Doppler will inject them
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
