apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobsight-pro
  namespace: jobsight
  labels:
    app: jobsight-pro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobsight-pro
  template:
    metadata:
      labels:
        app: jobsight-pro
    spec:
      containers:
        - name: jobsight-pro
          image: "${ACR_NAME}.azurecr.io/jobsight-pro:${IMAGE_TAG}"
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
            - name: ENVIRONMENT
              value: "production"

            # ✅ Non-sensitive values
            - name: KINDE_CLIENT_ID
              value: "${KINDE_CLIENT_ID}"
            - name: KINDE_ISSUER_URL
              value: "${KINDE_ISSUER_URL}"
            - name: KINDE_DOMAIN
              value: "${KINDE_DOMAIN}"
            - name: KINDE_SITE_URL
              value: "${KINDE_SITE_URL}"
            - name: KINDE_LOGOUT_REDIRECT_URI
              value: "${KINDE_LOGOUT_REDIRECT_URI}"
            - name: KINDE_POST_LOGOUT_REDIRECT_URL
              value: "${KINDE_POST_LOGOUT_REDIRECT_URL}"
            - name: KIDNE_REDIRECT_URI
              value: "${KIDNE_REDIRECT_URI}"
            - name: KINDE_POST_LOGIN_REDIRECT_URL
              value: "${KINDE_POST_LOGIN_REDIRECT_URL}"
            - name: SUPABASE_URL
              value: "${SUPABASE_URL}"

            # 🔐 Sensitive values from Kubernetes Secret
            - name: KINDE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jobsight-secrets
                  key: KINDE_CLIENT_SECRET
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: jobsight-secrets
                  key: SUPABASE_SERVICE_ROLE_KEY
            - name: OPENWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: jobsight-secrets
                  key: OPENWEATHER_API_KEY

          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
